const grilled = [
  {
    id: 1,
    name: 'Pork Barbeque',
    price: 25,
    image: '/assets/images/menu/grilled/pork-bbq.jpg',
    description: '',
  },
  {
    id: 2,
    name: 'Hotdog',
    price: 22,
    image: '/assets/images/menu/grilled/hotdog.jpg',
    description: '',
  },
  {
    id: 3,
    name: 'Isaw Manok',
    price: 12,
    image: '/assets/images/menu/grilled/isaw-manok.jpg',
    description: '',
  },
  {
    id: 4,
    name: 'Isaw Baboy',
    price: 15,
    image: '/assets/images/menu/grilled/isaw-baboy.jpg',
    description: '',
  },
  {
    id: 5,
    name: 'Isaw Baboy (bilog)',
    price: 20,
    image: '/assets/images/menu/grilled/isaw-bilog.jpg',
    description: '',
  },
  {
    id: 6,
    name: 'Leeg',
    price: 35,
    image: '/assets/images/menu/grilled/leeg.jpg',
    description: '',
  },
  {
    id: 7,
    name: 'Paa (Adidas)',
    price: 18,
    image: '/assets/images/menu/grilled/adidas.jpg',
    description: '',
  },
  {
    id: 8,
    name: 'Dugo (Betamax)',
    price: 12,
    image: '/assets/images/menu/grilled/betamax.jpg',
    description: '',
  },
  {
    id: 9,
    name: 'Chicharong Bulaklak',
    price: 19,
    image: '/assets/images/menu/grilled/chicharong-bulaklak.jpg',
    description: '',
  },
  {
    id: 10,
    name: 'Tenga',
    price: 23,
    image: '/assets/images/menu/grilled/tenga.jpg',
    description: '',
  },
];
